name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login $DOCKER_REGISTRY -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/dcbots/daichi:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/dcbots/daichi:buildcache,mode=max
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/dcbots/daichi:latest
            ${{ secrets.DOCKER_REGISTRY }}/dcbots/daichi:${{ github.sha }}
